### PR TITLE
Improvement on the /ns content

### PR DESCRIPTION
**Pull request by iherman**
- The ODRL22.nt and ODRL22.rdf files were empty; I have copied .ttl to .nt, and used a separate program to generate the RDF/XML version
- Added an ODRL22.html file that refers to the official specs

I have also uploaded these to /ns, and the redirections are now working properly.

### CODE REVIEW

**Review by riannella — COMMENTED** [review]
We don't directly support JSON. Only JSON-LD.
Should we add a link here to the JSON-LD context file as well?

**Comment by iherman** [comment]
Ah, then we should remove the json version from the list. Or, alternatively, add a jsonld version of the ontology (as opposed to the context file). I would be in favour of the latter (and my conversion program can produce, I believe, a json-ld version of the ontology).

Caveat: while the turtle file was carefully crafted to make readable for humans, the conversion to json-ld and rdf/xml is done by machine which doesn't make it readable...

**Comment by riannella** [comment]
I just found the magic to create the .rdf and .nt files
See the repo now

**Comment by riannella** [comment]
Ok, add the json-ld version of the ontology

**Review by riannella — APPROVED** [review]

**Pull request merged**
